### ISSUE TITLE
ValueError: dimension mismatch with EASE_R Model

### ISSUE THREAD

**Issue by ahmedrashed-ml** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#17]
Hi,

I am trying to run the EASE_R recommender on the Amazon Beauty dataset along with other baselines like Random, TopPop
 , and SLIMElasticNetRecommender using EvaluatorNegativeItemSample with 100 negatives. 

All baselines work just fine except the EASE_R which gives the below error. I also attached the database files for your reference

[Beauty.zip](https://github.com/MaurizioFD/RecSys2019_DeepLearning_Evaluation/files/5852606/Beauty.zip)

`Namespace(DL_article_default=True, ID=22, baseline_tune=True, print_results=True)
Dataset_Beauty: Attempting to load pre-splitted data
Dataset_Beauty: Dataset loaded
SearchBayesianSkopt: Resuming 'EASE_R_Recommender'... Loaded 2 configurations.
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0001
Function value obtained: 65504.0000
Current minimum: 65504.0000
Iteration No: 2 started. Evaluating function at random point.
EASE_R_Recommender: URM Detected 4 (0.03 %) cold items.
SearchBayesianSkopt: Testing config: {'topK': None, 'normalize_matrix': False, 'l2_norm': 2546768.2189065684}
EASE_R_Recommender: Fitting model... 
Unable to load Cython Compute_Similarity, reverting to Python
SearchBayesianSkopt: Config 2 Exception. Config: {'topK': None, 'normalize_matrix': False, 'l2_norm': 2546768.2189065684} - Exception: Traceback (most recent call last):
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 369, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 273, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 263, in _fit_model
    **current_fit_parameters)
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/EASE_R/EASE_R_Recommender.py", line 56, in fit
    grahm_matrix = similarity.compute_similarity().toarray()
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/Base/Similarity/Compute_Similarity.py", line 115, in compute_similarity
    return self.compute_similarity_object.compute_similarity(**args)
  File "/home/ahmed/Desktop/Projects/AreWe/Data/RecSys2019_DeepLearning_Evaluation/Base/Similarity/Compute_Similarity_Python.py", line 293, in compute_similarity
    this_block_weights = self.dataMatrix.T.dot(item_data)
  File "/home/ahmed/anaconda3/envs/DLevaluation/lib/python3.6/site-packages/scipy/sparse/base.py", line 364, in dot
    return self * other
  File "/home/ahmed/anaconda3/envs/DLevaluation/lib/python3.6/site-packages/scipy/sparse/base.py", line 518, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch

`

**Comment by MaurizioFD** [comment]
Hi,

I have noticed that the problem only occurs if you use the Python version of the similarity rather than the Cython one. The issue arises when only one item remains during the computation of the dot-product, which messes up some matrix shapes.

I'll try to fix it as soon as I can, in the meantime you can use the Cython version of the similarity (just run the compilation script), or replace the operation in EASER from this:
grahm_matrix = similarity.compute_similarity().toarray()
to this:
grahm_matrix = self.URM_train.dot(self.URM_train.T)

**Comment by ahmedrashed-ml** [comment]
Thank you so much for your clarification. I will try your proposed solution
